### ISSUE TITLE
Not able to add torrent file via web interface since last release

### ISSUE THREAD

**Issue by Gelioks** [6c65726f79/Transmissionic#1309]
**Describe the bug**
When adding a torrent file via web interface nothing happens.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on + in the right low corner
2. Click on the torrent file icon 
3. Select a torrent file from browser
4. Nothing happens, no popup window appears as it used to be before

**Platform:**
 - OS: macOS, iOS, iPadOS
 - Browser: Safari, Chrome
<img width="1003" alt="Screenshot 2023-03-17 at 14 30 07" src="https://user-images.githubusercontent.com/7465472/225919814-d5d2a063-bf73-4286-a1e2-109a731c9d9f.png">

The above messages appear in the browser console log

**Comment by 6c65726f79** [comment]
Have you tried to clear the cache by reloading the page with `Cmd` `Shift` `R` ?

**Comment by arnauos** [comment]
Same here, rolling back to 1.7.1 fixes it.

I see this message in the browser console when I try to add a torrent: 
`Unhandled Promise Rejection: Error: no web crypto support`

**Comment by bluskye** [comment]
Experiencing the same.  Adding via URL is working

**Comment by AnastasiyaSoyka** [comment]
Getting the same error on version 1.8.0; here's the log:

```txt
chunk-vendors.94715fc1.js:545 Uncaught (in promise) Error: no web crypto support
    at k (chunk-vendors.94715fc1.js:545:1354)
    at st (chunk-vendors.94715fc1.js:549:2098)
    at rt (chunk-vendors.94715fc1.js:549:396)
    at Object.parseBuffer (app.058545cd.js:1:65632)
    at Object.filesLoaded (app.058545cd.js:1:65483)
    at Object.readFiles (app.058545cd.js:1:65081)
```

**Comment by dlecan** [comment]
Same, Firefox, Chromium, Brave, when uploading a file

```
Uncaught (in promise) Error: no web crypto support
    k http://...js/chunk-vendors.94715fc1.js:545
    st http://...js/chunk-vendors.94715fc1.js:549
    rt http://...js/chunk-vendors.94715fc1.js:549
    parseBuffer http://...js/app.058545cd.js:1
    filesLoaded http://...js/app.058545cd.js:1
    readFiles http://...js/app.058545cd.js:1
    handleFiles http://...js/app.058545cd.js:1
    inputFile http://...js/app.058545cd.js:1
    inputFile http://...js/app.058545cd.js:1
    inputFile http://...js/app.058545cd.js:1
    5 http://...js/app.058545cd.js:1
    E http://...js/chunk-vendors.94715fc1.js:217
    a http://...js/chunk-vendors.94715fc1.js:217
    s http://...js/chunk-vendors.94715fc1.js:217
    s http://...js/chunk-vendors.94715fc1.js:217
    n http://...js/chunk-vendors.94715fc1.js:217
``

**Comment by remlio** [comment]
same in safari. adding via url and magnet working fine

**Comment by remlio** [comment]
hey folks, it’s working absolutely fine with ssl (https) connection. so you can set nginx server on reverse proxy to access transmission through https

**Comment by commonsons** [comment]
same here using edge and safari

**Comment by mocxi** [comment]
I have a same issue.

another workaround is using `localhost` (http://localhost:9091/transmission/web/)

**Comment by TheTitanius** [comment]
I also encountered this problem. For me, the solution was to roll back to version [1.6.1](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.6.1)
